### ISSUE TITLE
Mapa Mental - Edwin López Santiago

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/actividad-4-mapa-mental-calidad-de-software-Edwin14459#1]
[Mapa Mental - Edwin López Santiago.pdf](https://github.com/user-attachments/files/17092848/Mapa.Mental.-.Edwin.Lopez.Santiago.pdf)

**Comment by ka194** [comment]
Manejo conceptual y dominio del tema 18%
Relación entre los conceptos incluidos en el mapa 20 %
Calidad de la presentación 20 %
Jerarquía 20 %

Total: 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
